### ISSUE TITLE
`useWidgetViewFactory` always returns an undefined value

### ISSUE THREAD

**Issue by segfall** [Saul-Mirone/prosemirror-adapter#51]
Thank you for creating this repo. I was trying to build a custom editor I discovered that `useWidgetViewFactory` seems to work in React, but always seem to return an undefined value in Vue.

I've created a test environment which demonstrate this edgecase:
https://stackblitz.com/edit/github-rdvuhn?file=createEditorView.ts

Am I mis-using or misunderstanding how `useWidgetViewFactory` works?

**Comment by Saul-Mirone** [comment]
You need to wrap your editor with `ProsemirrorAdapterProvider`, something like https://github.com/Saul-Mirone/prosemirror-adapter/blob/main/examples/vue/App.vue#L8
