### ISSUE TITLE
[Feature request] Support for Angular

### ISSUE THREAD

**Issue by mggrand** [Saul-Mirone/prosemirror-adapter#54]
Is there any chance you could support angular? I love milkdown and your work around it. As I am forced to use angular for my project, I would love to see this adapter for angular. 

Thank you!

**Comment by mggrand** [comment]
@Saul-Mirone is there any chance that this is going to happen? I don't want to stress you out, I just want to weigh whether I should try to implement it myself or wait.

Thank you very much for all your work you have done to make using prosemirror more easy 🚀

**Comment by ousc** [comment]
> @Saul-Mirone这有可能发生吗？我不想给你压力，我只是想权衡一下我是应该尝试自己实现还是等待。
> 
> 非常感谢您为使 prosemirror 的使用变得更加容易而所做的所有工作🚀

I don't know if you have started implementing Angular adapters. I recently discovered Milkdown and this project, and I think it is a very meaningful work. I will try to complete it and propose a PR.

**Comment by ousc** [comment]
> @Saul-Mirone is there any chance that this is going to happen? I don't want to stress you out, I just want to weigh whether I should try to implement it myself or wait.
> 
> Thank you very much for all your work you have done to make using prosemirror more easy 🚀

I don't know if you have started implementing Angular adapters. I recently discovered Milkdown and this project, and I think it is a very meaningful work. I will try to complete it and propose a PR.
